version: "3"

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/app
    ports:
      - "5000:3000"
    depends_on:
      - server
