version: "3"

services:
  db:
    image: postgres:14
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/app
    ports:
      - "8090:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
