apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-db-migrate
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db-upgrade
          image: {{ .Values.server.deploy.containers.image}}
          imagePullPolicy: {{ .Values.server.deploy.containers.image}}
          command: ["alembic", "upgrade", "head"]
      restartPolicy: OnFailure
