apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.postgres.port }}
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}-postgres
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "postgres:14.3"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.postgres.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres_password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.name | quote }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
