apiVersion: v1
kind: Service
metadata:
 name: {{ include "chart.fullname" . }}-server
 labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: {{ include "chart.fullname" . }}-server
	{{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.server.service.ports.name }}
    port: {{ .Values.server.service.ports.port }}
    nodePort: {{ .Values.server.service.ports.nodePort }}
    targetPort: {{ .Values.server.service.ports.targetPort }}




